services:

  front:
    image: nginx
    ports:
      - 80:80
    working_dir: /app
    volumes: 
     - ./front:/app
    #command: sh -c "npm install && npm run dev"
    networks:
      - front-network

  back:
    image: directus/directus
    ports:
      - "8055:8055"
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET: ${SECRET}
      PUBLIC_URL: ${PUBLIC_URL}
    depends_on:
      - db 
        #condition: service_healthy
        #           service_started
    networks:
      - db-network
        

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: data-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    volumes:
    #- ./data/dump.sql:/docker-entrypoint-initdb.d/init.sql
    - db-data:/var/lib/postgresql/data
    networks:
      - db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha-dark
    depends_on:
      - db
    networks:
      - db-network


volumes:
  db-data:

networks:
  db-network:
  front-network: